# -*- coding: utf-8 -*-
"""Conexion GPT4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RObzazpeHZ-njckOonKISj3gjECE-0VU
"""

!pip install openai

import openai
from openai import OpenAI

client = OpenAI(api_key="your token")

messages = [{"role": "System", "content": "eres un informatico intentando aprender python"}]

input_message = input("en que te puedo ayudar")
messages.append({"role": "user", "content": input_message})
response = client.chat.completions.create(model="gpt-4o",
                                         messages=messages,
                                         temperature = 1,
                                         max_tokens = 150)

content = response.choices[0].message.content
formatted_response = f"El experto dice: {content}"
print(formatted_response)

